algoritmo "exercicio"

//Estou realizando exercicios para entender "enquanto"


var

Contagem : inteiro

inicio
// Vou dar uma certeza
Contagem <- 1 // aqui determino que contagem recebe 1

enquanto Contagem <= 128 faca // aqui uso o enquanto... faca!!
escreval("Iniciando Soma", Contagem) // aqui vai iniciar um looping até o valor
//dali de cima ser atingido!

 Contagem <- Contagem + Contagem
//aqui faço um calculo básico mas lembrando que contagem tem um valor ali!

fimenquanto


fimalgoritmo