Algoritmo "Exercicio"

Var
// Vamos lá será que dessa vez terá variaveis???

Contador : inteiro

Inicio
// aqui irei treinar tudo que ando aprendendo!

Contador <- 1

// agora vou executar a estrutura nova!

enquanto Contador <= 10 faca
     escreval("Numero", Contador)
     Contador <- Contador + 1
fimenquanto

// Essa estrutura vai realizar repetidamente uma contagem
//até o número que a variável contador recebeu!
// tive uma idéia de exercicio com esse negócio!


Fimalgoritmo