algoritmo "exercicios do GPT"

var
   // aqui estão as variaveis apresentadas até o momento
altura, raio, valorvolume : real

inicio
  // um cilinho?esses exercicios me deixam maluco
escreval("Escreva o raio do cilindro:")
leia(raio)
escreval("Escreva a altura do cilindro:")
leia(altura)

 //calculos
 
 valorvolume <- pi*raio^2*altura
 
 escreval("O volume desse cilindro é:", valorvolume:5:7)




fimalgoritmo