algoritmo "exercicios do GPT"

var


//meu pesadelo...
horas, minutos, segundos, duracaoEmSegundos : inteiro

inicio
//vamos começar com algo simples...

escreval("Digite uma quantidade em segundos para ser transformada no relógio:")
leia(duracaoEmSegundos)

//calculos da questão

horas <- duracaoEmSegundos/3600
minutos <- (duracaoEmSegundos\3600)/60
segundos <- duracaoEmSegundos\60

escreval(horas,":",minutos,":",segundos)




fimalgoritmo